# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170824_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='img/default.png', max_length=200, upload_to='static/img/%m', verbose_name='图片'),
        ),
    ]
