# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170824_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='static/images/ad/%m', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='images/img/default.png', max_length=200, upload_to='static/images/img/%m', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar/default.png', max_length=200, upload_to='static/images/avatar/%m', verbose_name='头像'),
        ),
    ]
